### ISSUE TITLE
Bloomberg graphs

### ISSUE THREAD

**Issue by jamiebyer** [jamiebyer/Climate#1]
- [ ] include some form of animation
- [ ] short descriptions of each single plot adjacent to or above the graph itself (radiobutton version)
- [ ] adding current data (for observations)(?)
- [ ] finding error bar data
- [x] display error bars
- [ ] attributions
- [ ] Reset button?
- [x] Change colour of all factors
- [x] Label observed temp
- [x] intro paragraph
- [x] File for markdown descriptions
- [x] Link to the original
- [x] default graph interactive
- [x] Tabs for "Learn" and "Explore"? (https://dash.plotly.com/dash-core-components/tabs)
- [ ] double click resets to correct y range

**Comment by fhmjones** [comment]
- [ ] radio buttons - why are they grouped? 
- [ ] Learn needs a reset or clear button. Or, if all 9 buttons are tied together, a 10th could be "none". 
- [ ] Axis is Temperature Anomaly, not Temperature. Intro text needs corresponding corrections. Also, temp anomaly probably should be explained, but that's just updating the introduction.md file. 
- [ ] JSON for curve descriptions is OK, but what are pros/cons of that versus markdown?
- [ ] How about coloured fonts for button labels to correspond with graph lines? If not too difficult. 
- [ ] "ID not found in layout" run-time error?
